apiVersion: v1
kind: Service
metadata:
  name: llama-exposed
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.42
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: llama-api-port
  selector:
    app: llama-cpp-server
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: llama-cpp-api
  labels:
    app: llama-cpp-server
spec:
  ports:
  - port: 8000
    name: tcp-llama-api
    protocol: TCP
    targetPort: llama-api-port
  type: NodePort
  selector:
    app: llama-cpp-server