apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: malwaretl-exposed
    metallb.universe.tf/loadBalancerIPs: 192.168.1.42
  labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: llama-cpp-server
    app.kubernetes.io/name: llama-cpp-exposed
  name: llama-cpp-server
  namespace: llama
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: tcp-llama-exposed-api
    port: 8000
    protocol: TCP
    targetPort: tcp-llama-api
  selector:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: llama-cpp-server
    app.kubernetes.io/name: llama-cpp-server
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: llama-cpp-api
  labels:
    app: llama-cpp-server
spec:
  ports:
  - port: 8000
    name: tcp-llama-api
    protocol: TCP
  type: NodePort
  selector:
    app: llama-cpp-server